### ISSUE TITLE
Publish Build Recipes

### ISSUE THREAD

**Issue by rsbeckerca** [ituglib/website-content#1]
We should be publishing the build recipes in the README files.

**Comment by rsbeckerca** [comment]
It might be better to include build recipes in the actual software. So far:
* For OpenSSL, this is documented in `NOTES-NONSTOP.md`.
* In git, simply running `make` will do it.
* Curl will require documentation once I figure out how to actually do it.
Others can follow.

**Comment by Jojo-Schmitz** [comment]
README.NONSTOP maybe

**Comment by rsbeckerca** [comment]
> 
> 
> README.NONSTOP maybe

Depends on the package. Each has their own standards for what they want to use.

**Comment by rsbeckerca** [comment]
I have done this for curl. openssl and git are documented internally to those packages.

**Comment by rsbeckerca** [comment]
This is basically done.
